name: Android ARMv7 Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install build tools (cmake, ninja)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK for armeabi-v7a
        env:
          ABI_FILTER: armeabi-v7a
        run: |
          echo "android {
            defaultConfig {
              ndk {
                abiFilters '${ABI_FILTER}'
              }
            }
          }" >> app/abi.gradle.kts

          echo "apply(from = \"abi.gradle.kts\")" >> app/build.gradle.kts

          ./gradlew :app:assembleDebug --stacktrace

      - name: Search for APKs
        run: find . -type f -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: armeabi-v7a-apk
          path: '**/*.apk'
